package:
  name: pygtk-textbuffer-with-undo
  version: 0.2

build:
  number: 1
  noarch: python
  script: pip install "pygtk-textbuffer-with-undo==0.2"

requirements:
  build:
    - python
    - pip

  run:
    - python
